server:
  port: 8000
  error:
    include-binding-errors: always
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: gateway filter
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3100"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

