server:
  port: 8002
url: www.greatjang.shop
spring:
  application:
    name: board

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/som
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_EMAIL}
    password: ${NAVER_PW}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none #update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: ${REDIS_HOST}
    port: 6379

jwt:
  expiration: 30
  secretKey: mysecret